# Generated by Django 2.2.5 on 2019-09-13 10:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import list.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True)),
                ('text', models.TextField(blank=True, db_index=True, help_text='Enter text', max_length=1000, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(default='media/photos/no_photo.jpg', upload_to=list.models.rename_post_image)),
                ('cost', models.IntegerField(help_text='Enter price')),
                ('employer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
