# Generated by Django 2.2.5 on 2019-09-14 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_from_vk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='from_vk',
        ),
    ]
